language: java
jdk:
  - openjdk17
before_install:
  - if [ ! -z "$TRAVIS_TAG" ]; then echo "on a tag -> set pom.xml <version> to $TRAVIS_TAG"; mvn org.codehaus.mojo:versions-maven-plugin:2.14.2:set -DnewVersion=$TRAVIS_TAG; else echo "not on a tag -> keep snapshot version in pom.xml"; fi
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test
deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "./target/ws-${TRAVIS_TAG}.jar"
  skip_cleanup: true
  on:
    tags: true
after_deploy:
  - ./scripts/trigger_travis_deploy.sh